# (PART) <lfg>LEARNING-SUPERVISED</lfg> {-}


# ECONOMETRIC REGRESSION STATIC

Econmetrics regression - models that explicitly show functional dependency between variables. 

## Linear model


## Nonlinear model
  
### with additive error term

### GLM

### GAM


## adding bayes

## mix effects

## multiple equations


# ECONOMETRIC REGRESSION DYNAMIC

## simple dynamic regression

## SARIMAX

## GARCH


Przyklad estymacji ARIMA_GARCH w R
[Time Series Analysis with ARIMA – ARCH/GARCH model in R](https://talksonmarkets.files.wordpress.com/2012/09/time-series-analysis-with-arima-e28093-arch013.pdf)

Praktyczne zastosownie modelu ARIMA-GARCH
[MODELING INFLATION VOLATILITY USING ARIMAX-GARCH](https://publikasiilmiah.ums.ac.id/bitstream/handle/11617/6312/b-10.pdf?sequence=3&isAllowed=y)




## Cointegration

## ARLD Applorach

## panel models

## error correction model (ECM VECM)

## multiple equations

### VARIMAX

### Structural VAR

### panel





# ANOVA / MANOVA / ANCOVA


# LDA QDA


# BAYESIAN NET


# CANONICAL ANALYSIS


# LATENT VARIABLES DETECTION


## Factor analysis

# SVM


# TREES


# BB-ensembled

## Bagging

## Boosting

## Stacking

## Twicing

## Bandling



# BB-neural networks



# OTHER DYNAMIC MODELS


## Basic trend models


## Basic adaptative models


## Spectral models


### Furies

### Walvets

### Singular Spectrum Analysis

[A beginner’s guide to SSA](http://environnement.ens.fr/IMG/file/DavidPDF/SSA_beginners_guide_v9.pdf)



## Martingales

## Bayesian filters and A Bayesian Structural Time Series Model

[The Two Stages of Bayes Filtering](https://www.youtube.com/watch?v=Qa8YMP9dQYo)

## Kalman Filters

[Special Topics - The Kalman Filter (1 of 55) What is a Kalman Filter](https://www.youtube.com/watch?v=CaCcOwJPytQ)

[Understanding Kalman Filters, Part 3: Optimal State Estimator](https://www.youtube.com/watch?v=ul3u2yLPwU0)


## Markov Provess

### Coninuous Time Markov Chains

[Continuous-Time Markov Chains in R](https://cran.r-project.org/web/packages/simmer/vignettes/simmer-07-ctmc.html]

## Winer Process


## Survival






# GENERAL ISSUES


## Algorithms per problems



### Numerical dependent

### Categorical Dependent

### Stochastic process

Przyklady modelowanie szeregow czasowych w excel. 
[Real Statistics Using Excel](http://www.real-statistics.com/time-series-analysis/)
[Są też pliki do pobrania](http://www.real-statistics.com/free-download/real-statistics-examples-workbook/)
Zeby arkusze poprawnie dzialaly trzeba sobie doinstalować w Excelu dodatek 'real-statistics-resource-pack'.


#### Casuation analysis

##### Cross correlation

##### Granger Casuation

More about casuality in part "BASICS".


Can Granger casuality test be applied to nonstationary Series?:

* [Granger causality test is applied on non stationary data or stationary data?](https://www.researchgate.net/post/Granger_causality_test_is_applied_on_non_stationary_data_or_stationary_da)ta 


#### Algoritm slection

Wymor metody analizy szeregu ze wzgledu na stacjonarnosc zmiennych:
* [Econometric model selection on the base of data stationary](https://www.youtube.com/watch?v=DSH5yclGf8M)
* [Tentative Time Series Model Selection Plan]https://nomanarshed.wordpress.com/2014/07/20/tentative-time-series-model-selection-plan/


### Images/Vides

### Text

### Sound


### numerical and categorical data

### Images/videos

### Text

### Sound


## Dignostics of models

[The proper way to use Machine Learning metrics](https://towardsdatascience.com/the-proper-way-to-use-machine-learning-metrics-4803247a2578)

### Conformal prediciton

[Conformal in R ](https://github.com/isidroc/conformal)


### Bias vs Variance

[Understanding the Bias-Variance Tradeoff](https://towardsdatascience.com/understanding-the-bias-variance-tradeoff-165e6942b229)


[MSE and Bias-Variance decomposition](https://towardsdatascience.com/mse-and-bias-variance-decomposition-77449dd2ff55)

[Bias-Variance Decomposition in Python](http://rasbt.github.io/mlxtend/user_guide/evaluate/bias_variance_decomp/)

## Variables selection

## IML
