# APPENDICIES

## Appendix A INDEX OF STATISTICAL TEST

## Appendix B Most important theorems in Statistics and probability calculus

### Central Limit

### Fisher-Tippett-Gnedenko

## Appendix C Different entries

### out-of-bag error

### hyperparameters

### information leakage

### apriori vs aposteriori

### colaborative filtering

### embedding

## Appendix D DICTIONARY POLISH - ENGLISH

loss function - funkcja straty

## Links - important

! - wykrzyknik oznacza wyjątkowo wartościowy materiał.

### books

[ksiazka do IML](https://christophm.github.io/interpretable-ml-book/)

[ksiazki w bookdownie](https://bookdown.org/)

[statystyka z R-em](https://benwhalley.github.io/just-enough-r/index.html)

[kasiazka Hastie](https://web.stanford.edu/~hastie/ElemStatLearn/)

[rozne ksiazki w PDF](https://1lib.eu/s/opencv)

[ekonometria w R](http://www.john-ros.com/Rcourse/)

książka o modelach predykcyjnych. Jest tutaj np. analiza reszt: [link](https://bookdown.org/egarpor/PM-UC3M/)

"Lab Guide to Quantitative Research Methods in Political Science, Public Policy & Public Administration": [link](https://bookdown.org/ripberjt/labbook/)

! ksiązka do machine learningu z przykładami w R [link](https://livebook.manning.com/book/machine-learning-for-mortals-mere-and-otherwise/about-this-book/)

### strony

[internetowy podręcznik StatSoft](https://www.statsoft.pl/textbook/stathome.html)

[lista rozkładów prawdopodobieństwa](https://www.wikiwand.com/en/List_of_probability_distributions)

[lista haseł statystycznych na wikipedii](https://www.wikiwand.com/en/List_of_statistics_articles)

[101 modeli w R](https://www.r-bloggers.com/2019/07/101-machine-learning-algorithms-for-data-science-with-cheat-sheets/)

[papers with code](https://paperswithcode.com/methods/)

[idre](https://stats.idre.ucla.edu/other/dae/)

[open AI blog](https://openai.com/blog/)

[machine leargnin mastery](https://machinelearningmastery.com/)

[kaggle](https://www.kaggle.com/)

[kaggle-blog](https://medium.com/kaggle-blog)

[pyimage search](https://www.pyimagesearch.com/)

[smartdatacollective](https://www.smartdatacollective.com/)

[whatsthebigdata](https://whatsthebigdata.com/)

[analyticsvidhya](https://www.analyticsvidhya.com/)

[AI news](https://allainews.com/)

[sci-hub](https://sci-hub.se/)

[towardsdatascience](https://towardsdatascience.com/)

[kdnuggets](https://www.kdnuggets.com/)

[web.vu.lt](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/) fajny podrecznik do ekonometrii. Są tutaj szczegółowo opisane np. modele GLM.

[explanatory model analysis](https://ema.drwhy.ai/)

[real statistics](https://www.real-statistics.com/free-download/real-statistics-resource-pack/) Jest tu omówiona factro analysis

[link](https://www.statsmodels.org/stable/stats.html) - lista metryk i statystyk w pakiecie *statsmodels*.

[link](https://mlr3book.mlr-org.com/index.html) manual do MLR pod R-em

[link](https://livecodestream.dev/post/top-data-science-blogs/) 10 najlepszych blogów

[DataScienceCentral](https://www.datasciencecentral.com/)

[SimplyStatistics](https://simplystatistics.org/)

[datafloq](https://datafloq.com/)

[ML Compiled](https://ml-compiled.readthedocs.io/en/latest/index.html) przegląd algorytmów ML.

! [link](https://www.geeksforgeeks.org/machine-learning/) lista przykładów algorytmów na geeksforgeeks:

### youtube

[StatQuest](https://www.youtube.com/user/joshstarmer)

[Kilcher - analizy artykulow](https://www.youtube.com/c/YannicKilcher/featured)

[deep learning ai](https://www.youtube.com/c/Deeplearningai/playlists) są tutaj wykłady Ng Andrew

[krishnaik](https://www.youtube.com/user/krishnaik06/videos)

[stanford machine learning](https://www.youtube.com/results?search_query=Stanford+CS229)

[KrishNaik](https://www.youtube.com/channel/UCNU_lfiiWBdtULKOw6X0Dig)

[ritvikmath](https://www.youtube.com/c/ritvikmath/videos) Bardzo dobry kanał ze szczegółami matematycznymi.

### narzedzia

[colab google](https://colab.research.google.com/notebooks/intro.ipynb#recent=true)

## **Ściąga latex**

SPACJA: \\,

boldowanie: \textbf{}

nowa linia: \\\\

+----------------------------------------------------------+--------------------------------------------------------------+
| Symbol                                                   | Kod                                                          |
+==========================================================+==============================================================+
| $\sum_{n=1}^{10}{x^2}$                                   | \sum\_{n=1}^{10}{x^2}                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\sum_{}^{}{x^2}$                                        | \sum\_{}^{}{x^2}                                             |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\prod_{n=1}^{10}{x}$                                    | \\prod\_{n=1}\^{10}{x}                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\int_{a}^{b} x^2 \,dx$                                  | \\int\_{a}\^{b} x\^2 \\,dx                                   |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\frac{1}{2}$                                            | \frac{1}{2}                                                  |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\begin{pmatrix} 1 & 2 & 3\\ a & b & c \\ \end{pmatrix}$ | \\begin{pmatrix} 1 & 2 & 3\\\\ a & b & c \\\\ \\end{pmatrix} |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\begin{Bmatrix} 1 & 2 & 3\\ a & b & c \\ \end{Bmatrix}$ | \\begin{Bmatrix} 1 & 2 & 3\\\\ a & b & c \\\\ \\end{Bmatrix} |
+----------------------------------------------------------+--------------------------------------------------------------+
| $z \in w$                                                | z \in w                                                      |
|                                                          |                                                              |
| $z \notin w$                                             | z \notin w                                                   |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\exists$                                                | \exists                                                      |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\forall$                                                | \forall                                                      |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\lor$                                                   | \\lor                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\land$                                                  | \land                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\neg$                                                   | \neg                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\Rightarrow$                                            | \\Rightarrow                                                 |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\subset$                                                | \subset                                                      |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\subseteq$                                              | \subseteq                                                    |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\infty$                                                 | infty                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\{$                                                     |                                                              |
|                                                          |                                                              |
| $\langle$                                                |                                                              |
|                                                          |                                                              |
| $\rangle$                                                |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\to$                                                    | \to                                                          |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\cup$                                                   | \cup                                                         |
|                                                          |                                                              |
| $\cap$                                                   | \cap                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\cong$                                                  | \cong                                                        |
|                                                          |                                                              |
| $\sim$                                                   | \sim                                                         |
|                                                          |                                                              |
| $\leq$                                                   | \leq                                                         |
|                                                          |                                                              |
| $\geq$                                                   | \geq                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\div$                                                   | \div                                                         |
|                                                          |                                                              |
| $\cdot$                                                  | \cdot                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\overline{A}$                                           | \overline{a}                                                 |
|                                                          |                                                              |
| $\hat{A}$                                                | \hat{A}}                                                     |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\underset{\gamma}{argmin}$                              | \\underset{\\gamma}{argmin}                                  |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\to$                                                    | \to                                                          |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\gamma$                                                 | \gamma                                                       |
|                                                          |                                                              |
| $\Gamma$                                                 | \Gamma                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\beta$                                                  | \beta                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\alpha$                                                 | \alpha                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\theta$                                                 | \theta                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\lambda$                                                | \lambda                                                      |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\epsilon$                                               | \epislon                                                     |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\zeta$                                                  | \zeta                                                        |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\omega$                                                 | \omega                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\partial$                                               | \partial                                                     |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\chi$                                                   | \chi                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\phi$                                                   | \phi                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\nabla$                                                 | \nabla                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\Omega$                                                 | \Omega                                                       |
+----------------------------------------------------------+--------------------------------------------------------------+
| $\Phi$                                                   | \Phi                                                         |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+
|                                                          |                                                              |
+----------------------------------------------------------+--------------------------------------------------------------+

```{=tex}
\frac{10}{10}
\cdot
\gamma
\beta
\theta
\hat{\theta}
```
## Courses notes

### Udacity

Warto używać przestrzni kolorów HSV i HSL.

W OpenCV kolory domyslnie sa ladownenie nie jako RGB ale jako BGR.

Canny Edge detector - etapy jego działania: [link](https://justin-liang.com/tutorials/canny/)

Ostatnia faza Canny detector (hystheresis) wymaga podania dwóch thresholdów.

HougLine detector jest dobrze stosować po Canny edges detector.
