# (PART) <lfg>APPENDIX</lfg> {-}


# LINSK - youtube

## Basic

* [machine learning](https://www.youtube.com/channel/UC5zx8Owijmv-bbhAK6Z9apg/videos) m.in wyklady Andrev Ng
* [StatQuest](https://www.youtube.com/user/joshstarmer/videos)
* [khan academy](https://www.youtube.com/results?search_query=khan+academy+playlists) playlista
* [mathematicalmonk](https://www.youtube.com/user/mathematicalmonk/videos) 
* []()


## Other


# LINKS web pages

## Basic

* [stackexchange](https://stats.stackexchange.com/)
* [arxiv](https://arxiv.org/)
* [toward dsta science](https://towardsdatascience.com/)
* [dae](https://stats.idre.ucla.edu/other/dae/) Przyklady modeli. Tutaj znalazlem np. multiple logistic regression w R 
* [analyticsvidhya](https://www.analyticsvidhya.com/blog/)
* (machine learning mastery)[https://machinelearningmastery.com/start-here/]
* [book down books](https://bookdown.org/)

## Wikipedia

* [wiki prob list](https://en.wikipedia.org/wiki/List_of_probability_topics) Lista hasel z rachunku prawdopodobienstwa
* [wiki prob calatog](https://en.wikipedia.org/wiki/Catalog_of_articles_in_probability_theory) Katalog hasel z rachunku prawdopodobienstwa 
* [wiki distributions](https://en.wikipedia.org/wiki/List_of_probability_distributions) Lista rozkladow
* [wiki stat](https://en.wikipedia.org/wiki/List_of_statistics_articles) Katalog hasel ze statysyki


## Bookdown books:

* [Sanjiv Ranjan](https://srdas.github.io/MLBook/) ML w R. Book by Sanjiv Ranjan Das
* [iml book](https://christophm.github.io/interpretable-ml-book/) Book about IML
* [Modelowanie w R]http://www.john-ros.com/Rcourse/lme.html
* [ekonometria](http://www.john-ros.com/Rcourse/lme.html)ekonometria w R
* [szeregi](https://otexts.com/fpp2/) szeregi czasowe w R

## Other

* [jurnal of machine learning](http://www.jmlr.org/)
* [odelama](http://www.odelama.com/data-analysis/). Fajna strona z podstawowymi wzorami np. z rachunku prawdopowobieństwa: 

## github

* [Damian](https://github.com/s3nh)
* [Adrian](https://github.com/xadrianzetx?tab=repositories)

# DICTIONARY


